"""
Drive the Hunyuan3D shape batch.

    python generate_meshes.py <ENDPOINT_URL> [batch_dir]

Reads the reference PNGs generated by Klein, sends them as base64 in a single
request (one cold start for the whole batch), and prints the face counts before
and after decimation so the triangle budget stays visible.

Token comes from ~/.beam/config.ini and is never printed.
"""

import base64
import configparser
import io
import json
import os
import sys
import time
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))


def beam_token(context="default"):
    cfg = configparser.ConfigParser()
    cfg.read(os.path.expanduser("~/.beam/config.ini"))
    if context not in cfg or "token" not in cfg[context]:
        sys.exit("No Beam token in ~/.beam/config.ini")
    return cfg[context]["token"]


def main():
    if len(sys.argv) < 2:
        sys.exit(__doc__)

    url = sys.argv[1]
    batch = sys.argv[2] if len(sys.argv) > 2 else "vehicles_v1"
    src = os.path.join(HERE, "out", batch)
    if not os.path.isdir(src):
        sys.exit(f"No such batch: {src}")

    # Downscale and re-encode as JPEG before sending. A batch of 1024px PNGs is
    # ~16MB of base64, which the connection kept dropping; the shape model does
    # not benefit from that resolution anyway.
    from PIL import Image as PILImage

    only = os.environ.get("ONLY")          # ONLY=car_sedan to send a single one
    jobs = []
    for fn in sorted(os.listdir(src)):
        if not fn.lower().endswith(".png"):
            continue
        jid = os.path.splitext(fn)[0]
        if only and jid != only:
            continue
        im = PILImage.open(os.path.join(src, fn)).convert("RGB")
        im.thumbnail((768, 768), PILImage.LANCZOS)
        buf = io.BytesIO()
        im.save(buf, "JPEG", quality=92)
        jobs.append({"id": jid, "image_b64": base64.b64encode(buf.getvalue()).decode()})

    if not jobs:
        sys.exit(f"No PNGs in {src}")

    payload = {
        "jobs": jobs,
        "out": batch,
        "steps": 12,
        "octree_resolution": 256,
        "face_budget": 1800,
    }

    mb = sum(len(j["image_b64"]) for j in jobs) / 1_000_000
    print(f"Sending {len(jobs)} reference images ({mb:.1f} MB base64) -> {batch}")
    print("First call pays a cold start: container boot plus the shape model "
          "loading off the volume.\n")

    req = urllib.request.Request(
        url,
        data=json.dumps(payload).encode(),
        headers={"Authorization": f"Bearer {beam_token()}",
                 "Content-Type": "application/json"},
        method="POST",
    )

    t0 = time.time()
    try:
        with urllib.request.urlopen(req, timeout=1800) as r:
            result = json.loads(r.read())
    except urllib.error.HTTPError as e:
        sys.exit(f"HTTP {e.code}: {e.read().decode()[:1500]}")

    wall = time.time() - t0

    if "error" in result:
        sys.exit(f"Endpoint error: {result['error']}")

    print(f"{'id':<20}{'faces raw':>11}{'faces':>8}{'KB':>8}{'gen s':>8}")
    print("-" * 55)
    for m in result["meshes"]:
        print(f"{m['id']:<20}{m['faces_raw']:>11}{m['faces']:>8}"
              f"{m['kb']:>8.0f}{m['gen_s']:>8.1f}")
    print("-" * 55)
    total_faces = sum(m["faces"] for m in result["meshes"])
    total_kb = sum(m["kb"] for m in result["meshes"])
    print(f"GPU time    : {result['total_seconds']:.1f}s")
    print(f"Wall clock  : {wall:.1f}s")
    print(f"All meshes  : {total_faces} faces, {total_kb:.0f} KB")
    print(f"\nPull them down with:\n  python pull_meshes.py {batch}")


if __name__ == "__main__":
    main()
